# Preparando base de dados

A base de dados é composta por dados relacionados aos alunos do integrado de todos os campis geradas em janeiro de 2018.

In [70]:
#importar os pacotes utilizados
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

#exibindo todas as colunas
pd.set_option('display.max_columns', None)

In [96]:
#definindo funcoes
import re
def clean_string(string):
    cleanString = re.sub('\W+','', string)
    cleanString = re.sub(r'[^a-zA-Z0-9 ]',r'',cleanString)

    return cleanString

from datetime import datetime
from datetime import date, timedelta

def get_age(born):
    b = datetime.strptime(born, "%d/%m/%Y")
    age = (date.today() - b.date()) // timedelta(days=365.2425)
    return age

In [2]:
#importar os dados em formato json e transforma em dataframe do pandas
df_AcompanhamentoEncaminhamento = pd.read_json('dados/AcompanhamentoEncaminhamento.json')
df_Aluno = pd.read_json('dados/Aluno.json')
df_BeneficioGovernoFederal = pd.read_json("dados/BeneficioGovernoFederal.json")
df_Caracterizacao = pd.read_json("dados/Caracterizacao.json")
df_CompanhiaDomiciliar = pd.read_json("dados/CompanhiaDomiciliar.json")
df_ContribuinteRendaFamiliar = pd.read_json("dados/ContribuinteRendaFamiliar.json")
df_CursoCampus = pd.read_json('dados/CursoCampus.json')
df_CursoFormacaoSuperior = pd.read_json('dados/CursoFormacaoSuperior.json')
df_Disciplina = pd.read_json("dados/Disciplina.json")
df_Encaminhamento = pd.read_json("dados/Encaminhamento.json")
df_EstadoCivil = pd.read_json("dados/EstadoCivil.json")
df_Idioma = pd.read_json("dados/Idioma.json")
df_MatriculaPeriodo = pd.read_json("dados/MatriculaPeriodo.json")
df_MeioTransporte = pd.read_json("dados/MeioTransporte.json")
df_NecessidadeEspecial = pd.read_json("dados/NecessidadeEspecial.json")
df_NivelEscolaridade = pd.read_json("dados/NivelEscolaridade.json")
df_Notas = pd.read_json("dados/Notas.json")
df_Professores = pd.read_json("dados/Professores.json")
df_Raca = pd.read_json("dados/Raca.json")
df_RazaoAfastamentoEducacional = pd.read_json("dados/RazaoAfastamentoEducacional.json")
df_SituacaoDisciplina = pd.read_json("dados/SituacaoDisciplina.json")
df_SituacaoMatricula = pd.read_json("dados/SituacaoMatricula.json")
df_SituacaoMatriculaPeriodo = pd.read_json("dados/SituacaoMatriculaPeriodo.json")
df_SituacaoTrabalho = pd.read_json("dados/SituacaoTrabalho.json")
df_TipoAcessoInternet = pd.read_json("dados/TipoAcessoInternet.json")
df_TipoAreaResidencial = pd.read_json("dados/TipoAreaResidencial.json")
df_TipoEscola = pd.read_json("dados/TipoEscola.json")
df_TipoImovelResidencial = pd.read_json("dados/TipoImovelResidencial.json")
df_TipoServicoSaude = pd.read_json("dados/TipoServicoSaude.json")
df_UnidadeOrganizacional = pd.read_json("dados/UnidadeOrganizacional.json")

In [3]:
#imprime duas linhas de cada dataframe para exibir a organização dos dados
print("df_AcompanhamentoEncaminhamento")
print(df_AcompanhamentoEncaminhamento.head(2))
print("df_Aluno")
print(df_Aluno.head(2))
print("df_BeneficioGovernoFederal")
print(df_BeneficioGovernoFederal.head(2))
print("df_Caracterizacao")
print(df_Caracterizacao.head(2))
print("df_CompanhiaDomiciliar")
print(df_CompanhiaDomiciliar.head(2))
print("df_ContribuinteRendaFamiliar")
print(df_ContribuinteRendaFamiliar.head(2))
print("df_CursoCampus")
print(df_CursoCampus.head(2))
print("df_CursoFormacaoSuperior")
print(df_CursoFormacaoSuperior.head(2))
print("df_Disciplina")
print(df_Disciplina.head(2))
print("df_Encaminhamento")
print(df_Encaminhamento.head(2))
print("df_EstadoCivil")
print(df_EstadoCivil.head(2))
print("df_Idioma")
print(df_Idioma.head(2))
print("df_MatriculaPeriodo")
print(df_MatriculaPeriodo.head(2))
print("df_MeioTransporte")
print(df_MeioTransporte.head(2))
print("df_NecessidadeEspecial")
print(df_NecessidadeEspecial.head(2))
print("df_NivelEscolaridade")
print(df_NivelEscolaridade.head(2))
print("df_Notas")
print(df_Notas.head(2))
print("df_Professores")
print(df_Professores.head(2))
print("df_Raca")
print(df_Raca.head(2))
print("df_RazaoAfastamentoEducacional")
print(df_RazaoAfastamentoEducacional.head(2))
print("df_SituacaoDisciplina")
print(df_SituacaoDisciplina.head(2))
print("df_SituacaoMatricula")
print(df_SituacaoMatricula.head(2))
print("df_SituacaoMatriculaPeriodo")
print(df_SituacaoMatriculaPeriodo.head(2))
print("df_SituacaoTrabalho")
print(df_SituacaoTrabalho.head(2))
print("df_TipoAcessoInternet")
print(df_TipoAcessoInternet.head(2))
print("df_TipoAreaResidencial")
print(df_TipoAreaResidencial.head(2))
print("df_TipoEscola")
print(df_TipoEscola.head(2))
print("df_TipoImovelResidencial")
print(df_TipoImovelResidencial.head(2))
print("df_TipoServicoSaude")
print(df_TipoServicoSaude.head(2))
print("df_UnidadeOrganizacional")
print(df_UnidadeOrganizacional.head(2))

df_AcompanhamentoEncaminhamento
   acompanhamento__aluno_id        data  encaminhamento_id          id
0              507223381477  07/07/2017          946008521  7096627713
1              452389189433  07/07/2017          934855993  7099415845
df_Aluno
   ano_letivo__ano        cep cidade__estado__nome cidade__nome  \
0             2018  59535-000  RIO GRANDE DO NORTE        LAJES
1             2018  59170-000  RIO GRANDE DO NORTE         ARÊS

   curso_campus_id            id  periodo_letivo  \
0       3282463137  613557159693               1
1       3299191929  615294165929               1

  pessoa_fisica__nascimento_data pessoa_fisica__sexo  situacao_id
0                     08/07/2002                   M    920915333
1                     16/04/2001                   M    920915333
df_BeneficioGovernoFederal
                                          descricao         id
0  Programa Benefício de Prestação Continuada - BPC  932067861
1                            Programa Bolsa Família  926491597
df_Caracterizacao
   aluno_exclusivo_rede_publica      aluno_id  companhia_domiciliar_id  \
0                         False  454602966241                937644125
1                         False  541910531689                937644125

   ensino_fundamental_conclusao  ensino_medio_conclusao  \
0                          2013                     0.0
1                          2016                     NaN

   escola_ensino_fundamental_id  escola_ensino_medio_id  estado_civil_id  \
0                   923703465.0                     NaN        934855993
1                   920915333.0                     NaN        934855993

   ficou_tempo_sem_estudar  frequencia_acesso_internet_id  \
0                      0.0                    920915333.0
1                      1.0                    920915333.0

   historico_caracterizacao_id            id local_acesso_internet  \
0                  80477473821   89920876905               celular
1                 205826312277  214620080605                Escola

   mae_nivel_escolaridade_id  \
0                  965525445
1                  959949181

                      nome_escola_ensino_fundamental nome_escola_ensino_medio  \
0                    Escola Estadual Mauricio Freire
1  Escola Municipal Desembargador Silvino Bezerra...

   pai_nivel_escolaridade_id  possui_conhecimento_idiomas  \
0                  962737313                    920915333
1                  959949181                            0

   possui_conhecimento_informatica  possui_necessidade_especial  qtd_filhos  \
0                              1.0                        False           0
1                              1.0                        False           0

   qtd_pessoas_domicilio  quantidade_computadores  quantidade_netbooks  \
0                      4                      0.0                  0.0
1                      4                      0.0                  0.0

   quantidade_notebooks  quantidade_smartphones    raca_id  \
0                   0.0                     1.0  920915333
1                   0.0                     1.0  923703465

   razao_ausencia_educacional_id  renda_bruta_familiar  renda_per_capita  \
0                            NaN                880.00              0.28
1                            NaN               2037.35              0.54

   responsavel_financeir_trabalho_situacao_id  responsavel_financeiro_id  \
0                                   951584785                  946008521
1                                   937644125                  946008521

   responsavel_financeiro_nivel_escolaridade_id  tempo_sem_estudar  \
0                                     962737313                NaN
1                                     959949181                NaN

   tipo_area_residencial_id  tipo_imovel_residencial_id  \
0                 932067861                   934855993
1                 932067861                   934855993

   tipo_servico_saude_id  trabalho_situacao_id
0            926491597.0             940432257
1            926491597.0             943220389
df_CompanhiaDomiciliar
  descricao         id
0       Pai  954372917
1       Mãe  957161049
df_ContribuinteRendaFamiliar
  descricao         id
0       Pai  946008521
1       Mãe  948796653
df_CursoCampus
                         descricao_historico  diretoria__setor__uo_id  \
0  Técnico de Nivel Médio em Biocombustíveis                940432257
1     Técnico de Nível Médio em Agroecologia                934855993

           id
0  1927430985
1  1877244609
df_CursoFormacaoSuperior
   codigo                    descricao         grau
0  345A01  Administração - Bacharelado  Bacharelado
1  621A04      Agronomia - Bacharelado  Bacharelado
df_Disciplina
   ch_hora_relogio                          descricao_historico           id
0              120                       Acionamento Eletrônico  11613401553
1               60  Administração de Empresas Cooperativistas I  11195181753
df_Encaminhamento
                                        descricao         id
0                          Atendimento domiciliar  951584785
1  Contato telefônico com os pais ou responsáveis  934855993
df_EstadoCivil
     descricao         id
0  Solteiro(a)  934855993
1    Casado(a)  937644125
df_Idioma
  descricao         id  uso_caracterizacao
0    Inglês  932067861                True
1  Espanhol  934855993                True
df_MatriculaPeriodo
       aluno_id  ano_letivo__ano             id  periodo_letivo  situacao_id
0  576628351353             2010  1551350934157               1    948796653
1  464294513073             2011  1062122988381               1    948796653
df_MeioTransporte
           descricao         id
0  Transporte locado  965525445
1          Bicicleta  943220389
df_NecessidadeEspecial
  descricao         id
0  Auditiva  940432257
1    Física  943220389
df_NivelEscolaridade
                     descricao         id
0                 Alfabetizado  954372917
1  Ensino fundamental completo  957161049
df_Notas
   disciplina_id  matricula_periodo_id  media_final  percentual_frequencia  \
0     9792751357         1289149424613           95                   98.0
1     9795539489         1479082552717           93                   90.0

         professores  situacao_id
0  [1510, 1622, 802]    923703465
1             [1436]    923703465
df_Professores
  codigo_curso_formacao_superior data_ingresso           id  \
0                           None    21/03/2016  11529757593
1                         142P01    26/06/2014   8939582965

                regime     titulacao
0    40 HORAS SEMANAIS        Mestre
1  DEDICACAO EXCLUSIVA  Especialista
df_Raca
   codigo_censup  codigo_siape descricao         id  inativo_siape
0              3             4     Parda  920915333          False
1              2             6     Preta  923703465          False
df_RazaoAfastamentoEducacional
                                           descricao         id
0                                 Falta de Motivação  940432257
1  Baixa condição financeira para se manter na es...  937644125
df_SituacaoDisciplina
  descricao         id
0  Cursando  920915333
1  Aprovado  923703465
df_SituacaoMatricula
                    descricao         id
0                    Afastado  940432257
1  Aguardando Colação de Grau  954372917
df_SituacaoMatriculaPeriodo
  descricao         id
0  Afastado  932067861
1  Aprovado  948796653
df_SituacaoTrabalho
              descricao         id
0              Autônomo  937644125
1  Não está trabalhando  940432257
df_TipoAcessoInternet
          descricao         id
0       Diariamente  920915333
1  A cada dois dias  923703465
df_TipoAreaResidencial
  descricao         id
0    Urbana  932067861
1     Rural  934855993
df_TipoEscola
                         descricao         id
0        Somente em escola pública  920915333
1  A maior parte em escola pública  923703465
df_TipoImovelResidencial
                  descricao         id
0  Pensionato ou Alojamento  948796653
1                     Outro  951584785
df_TipoServicoSaude
                   descricao         id
0  Plano de saúde particular  920915333
1  Plano de saúde da empresa  923703465
df_UnidadeOrganizacional
          id sigla
0  940432257    AP
1  937644125    CA

# Merge entre os arquivos json

Realiza o merge dos dados (similiar ao join do sql), o qual, a partir de dois dataframes, é gerado um terceiro 
com os atributos dos dois anteriores ligados por algum campo em comum.

In [14]:
#df_Alunos shape: (11311, 10)
print(df_Aluno.shape) 

#relacionando aluno ao seu campus
dados = pd.merge(df_Aluno, df_CursoCampus, 
                 left_on="curso_campus_id", right_on="id", suffixes=["", "_curso_campus"])
dados = pd.merge(dados, df_UnidadeOrganizacional, 
                 left_on="diretoria__setor__uo_id", right_on="id", suffixes=["", "_unidade_organizacional"])

#relacionando o aluno com sua situacao de matricula
dados = pd.merge(dados, df_SituacaoMatricula, 
                 left_on="situacao_id", right_on="id", suffixes=["", "_situacao_matricula"])
print(dados.shape)

#relacionando aluno aos dados de caracterizacao social
dados = pd.merge(dados, df_Caracterizacao, 
                 left_on="id", right_on="aluno_id", suffixes=["", "_caracterizacao"])
dados = pd.merge(dados, df_CompanhiaDomiciliar, 
                 left_on="companhia_domiciliar_id", right_on="id", suffixes=["", "_companhia_domiciliar"])
dados = pd.merge(dados, df_EstadoCivil, 
                 left_on="estado_civil_id", right_on="id", suffixes=["", "_estado_civil"])
dados = pd.merge(dados, df_TipoAcessoInternet, how='left', 
                 left_on="frequencia_acesso_internet_id", right_on="id", suffixes=["", "_internet"])
dados = pd.merge(dados, df_NivelEscolaridade, 
                 left_on="mae_nivel_escolaridade_id", right_on="id", suffixes=["", "_mae_escolaridade"])
dados = pd.merge(dados, df_NivelEscolaridade, 
                 left_on="pai_nivel_escolaridade_id", right_on="id", suffixes=["", "_pai_escolaridade"])
dados = pd.merge(dados, df_Raca, 
                 left_on="raca_id", right_on="id", suffixes=["", "_raca"])
dados = pd.merge(dados, df_RazaoAfastamentoEducacional, how='left', 
                 left_on="razao_ausencia_educacional_id", right_on="id", suffixes=["", "_afastamento"])
dados = pd.merge(dados, df_SituacaoTrabalho,
                 left_on="responsavel_financeir_trabalho_situacao_id", right_on="id", suffixes=["", "_trabalho_responsavel"])
dados = pd.merge(dados, df_ContribuinteRendaFamiliar, 
                 left_on="responsavel_financeiro_id", right_on="id", suffixes=["", "_responsavel_financeiro"])
dados = pd.merge(dados, df_NivelEscolaridade, 
                 left_on="responsavel_financeiro_nivel_escolaridade_id", right_on="id", suffixes=["", "_responsavel_escolaridade"])
dados = pd.merge(dados, df_TipoAreaResidencial, 
                 left_on="tipo_area_residencial_id", right_on="id", suffixes=["", "_area_residencial"])
dados = pd.merge(dados, df_TipoImovelResidencial, 
                 left_on="tipo_imovel_residencial_id", right_on="id", suffixes=["", "_imovel"])
dados = pd.merge(dados, df_TipoServicoSaude, how='left', 
                 left_on="tipo_servico_saude_id", right_on="id", suffixes=["", "_saude"])
dados = pd.merge(dados, df_SituacaoTrabalho,  
                 left_on="trabalho_situacao_id", right_on="id", suffixes=["", "_trabalho"])
print(dados.shape)
#dados.head(2)

#selecionando os campos no dataframe
dados = dados[['id', 
               'ano_letivo__ano', 
               'cep', 
               'pessoa_fisica__nascimento_data', 
               'pessoa_fisica__sexo', 
               'descricao_historico', 
               'sigla',
               'descricao', 
               'aluno_exclusivo_rede_publica',
               'ensino_fundamental_conclusao', 
               'ficou_tempo_sem_estudar',
               'local_acesso_internet', 
               'possui_conhecimento_informatica', 
               'possui_necessidade_especial', 
               'qtd_pessoas_domicilio', 
               'quantidade_computadores', 
               'quantidade_netbooks', 
               'quantidade_notebooks', 
               'quantidade_smartphones', 
               'renda_bruta_familiar',
               'descricao_companhia_domiciliar', 
               'descricao_estado_civil', 
               'descricao_internet', 
               'descricao_mae_escolaridade', 
               'descricao_pai_escolaridade', 
               'descricao_raca', 
               'descricao_responsavel_financeiro', 
               'descricao_responsavel_escolaridade', 
               'descricao_area_residencial', 
               'descricao_imovel', 
               'descricao_saude', 
               'descricao_trabalho', 
              ]]

print(dados.id.nunique())
print(dados.shape)
dados.head(3)

(11311, 10)
(11311, 17)
(9511, 86)

,id,ano_letivo__ano,cep,pessoa_fisica__nascimento_data,pessoa_fisica__sexo,descricao_historico,sigla,descricao,aluno_exclusivo_rede_publica,ensino_fundamental_conclusao,ficou_tempo_sem_estudar,local_acesso_internet,possui_conhecimento_informatica,possui_necessidade_especial,qtd_pessoas_domicilio,quantidade_computadores,quantidade_netbooks,quantidade_notebooks,quantidade_smartphones,renda_bruta_familiar,descricao_companhia_domiciliar,descricao_estado_civil,descricao_internet,descricao_mae_escolaridade,descricao_pai_escolaridade,descricao_raca,descricao_responsavel_financeiro,descricao_responsavel_escolaridade,descricao_area_residencial,descricao_imovel,descricao_saude,descricao_trabalho
0,457884597605,2015,59535-000,22/10/1999,F,Técnico de Nivel Médio em Informática,LAJ,Matriculado,False,2014,0.0,NA ESCOLA E EM CASA.,1.0,False,2,0.0,0.0,0.0,1.0,300.0,Mãe,Solteiro(a),Diariamente,Ensino fundamental incompleto,Ensino fundamental incompleto,Branca,Mãe,Ensino fundamental incompleto,Urbana,Alugado,Sistema Único de Saúde - SUS,Não informado
1,458436647741,2015,59460-000,04/10/1997,M,Técnico de Nível Médio em Meio Ambiente,SPP,Cancelado,False,2013,0.0,casa da avó,NaN,False,2,0.0,0.0,1.0,1.0,0.0,Mãe,Solteiro(a),Diariamente,Ensino fundamental incompleto,Ensino fundamental incompleto,Parda,Mãe,Ensino fundamental incompleto,Urbana,Alugado,Sistema Único de Saúde - SUS,Não informado
2,557485037041,2017,59390-000,14/02/2000,M,Técnico de Nivel Médio em Informática,CN,Matriculado,False,2016,0.0,Minha casa.,1.0,False,5,0.0,0.0,1.0,1.0,400.0,Mãe,Solteiro(a),Diariamente,Ensino fundamental incompleto,Ensino fundamental incompleto,Preta,Mãe,Ensino fundamental incompleto,Urbana,Alugado,Sistema Único de Saúde - SUS,Não informado

# Recuperando notas

In [28]:
#relacionando aluno a situacao da matricula naquele periodo
dados_notas = pd.merge(dados, df_MatriculaPeriodo, 
                 left_on="id", right_on="aluno_id", suffixes=["", "_matricula_periodo"])

dados_notas = pd.merge(dados_notas, df_SituacaoMatriculaPeriodo, 
                 left_on="situacao_id", right_on="id", suffixes=["", "_situacao_matricula_periodo"])
print(dados_notas.shape)

#relacionando aluno a nota das disciplinas daquele periodo
dados_notas = pd.merge(dados_notas, df_Notas, 
                 left_on="id_matricula_periodo", right_on="matricula_periodo_id", suffixes=["", "_notas"])
dados_notas = pd.merge(dados_notas, df_Disciplina, 
                 left_on="disciplina_id", right_on="id", suffixes=["", "_disciplina"])

dados_notas = dados_notas[['id', 'descricao_historico_disciplina', 'percentual_frequencia', 'media_final']]

print(dados_notas.shape)
dados_notas.head(2)

(22466, 39)
(188544, 4)

,id,descricao_historico_disciplina,percentual_frequencia,media_final
0,457884597605,Informática(45H),100.0,74
1,458436647741,Informática(45H),100.0,68

serão apenas utilizados as notas de português e matemática do 1º ano

In [32]:
dados_filtrado = dados_notas[(dados_notas.descricao_historico_disciplina.str.startswith('Língua Portuguesa')) | 
              (dados_notas.descricao_historico_disciplina.str.startswith('Matemática I')) ]
print(dados_filtrado.shape)
dados_filtrado.head(2)


dados_filtrado["descricao_historico_disciplina"].value_counts()

(27580, 4)

Matemática I(120H)                         9418
Língua Portuguesa e Literatura I(90H)      8283
Matemática II(90H)                         3943
Língua Portuguesa e Literatura II(90H)     3797
Matemática III(90H)                        1033
Língua Portuguesa e Literatura III(90H)    1027
Língua Portuguesa e Literatura IV(60H)       44
Matemática II(120H)                          34
Língua Portuguesa e Literatura IV             1
Name: descricao_historico_disciplina, dtype: int64

In [48]:
dados[ clean_string('Matemática I(120H)') ] = np.ones(dados.shape[0])*-1 
dados[ clean_string('Matemática I(120H)') + '_freq' ] = np.ones(dados.shape[0])*-1
dados[ clean_string('Matemática I(120H)') + '_dependencia' ] = np.ones(dados.shape[0])*-1

dados[ clean_string('Língua Portuguesa e Literatura I(90H)') ] = np.ones(dados.shape[0])*-1 
dados[ clean_string('Língua Portuguesa e Literatura I(90H)') + '_freq' ] = np.ones(dados.shape[0])*-1 
dados[ clean_string('Língua Portuguesa e Literatura I(90H)') + '_dependencia' ] = np.ones(dados.shape[0])*-1 

dados[ 'idade' ] = np.ones(dados.shape[0])*-1

In [98]:
#para cada aluno recupera a nota de Português e Matemática do 1º ano. Caso o mesmo tenha tido dependência salva a nota mais alta
for i in dados.id:
    
    #recupera a nota de matematica e atribui ao aluno
    r_mat = dados_filtrado[(dados_filtrado.id == i) & (dados_filtrado.descricao_historico_disciplina == 'Matemática I(120H)')]
    dados.loc[dados.id == i, clean_string('Matemática I(120H)') ] = r_mat.media_final.max()
    dados.loc[dados.id == i, clean_string('Matemática I(120H)') + '_freq' ] = r_mat.percentual_frequencia.max()  
    dados.loc[dados.id == i, clean_string('Matemática I(120H)') + '_dependencia' ] = r_mat.shape[0] - 1

    #recupera a nota de portugues e atribui ao aluno
    r_por = dados_filtrado[(dados_filtrado.id == i) & 
                           (dados_filtrado.descricao_historico_disciplina == 'Língua Portuguesa e Literatura I(90H)')]
    dados.loc[dados.id == i, clean_string('Língua Portuguesa e Literatura I(90H)') ] = r_por.media_final.max() 
    dados.loc[dados.id == i, clean_string('Língua Portuguesa e Literatura I(90H)') + '_freq' ] = r_por.percentual_frequencia.max() 
    dados.loc[dados.id == i, clean_string('Língua Portuguesa e Literatura I(90H)') + '_dependencia' ] = r_mat.shape[0] - 1 
    
    
    #gerando idade de cada aluno
    #dados.loc[dados.id == i, 'idade'] = get_age(dados.loc[dados.id == i, 'pessoa_fisica__nascimento_data']) 
    
    #print(i)
    #print(dados[dados.id == i].MatemticaI120H)
    
dados.head(3)

TypeError: strptime() argument 1 must be str, not Series

In [99]:
dados['idade'] = get_age(dados.pessoa_fisica__nascimento_data)

TypeError: strptime() argument 1 must be str, not Series